### ISSUE TITLE
Translated text revert to original when hiding translation bar

### ISSUE THREAD

**Issue by Undisputed00x** [im030/Momogram#27]
**Describe the bug**
As the title says, when try to hide the translation bar by pressing "Hide" in the contenxt menu, translated text reverts to its original form.

**Expected behavior**
When pressing "Hide" in the Translation bar, don't make auto-translated text revert to the original language

<details>
<summary>

### Screenshots

</summary>
<p>

![Screenshot_20241113-161238](https://github.com/user-attachments/assets/d5ce4674-b814-467f-a0de-2242882470ba)

![Screenshot_20241113-161306](https://github.com/user-attachments/assets/4b9aaefc-1c30-4ea9-9661-34d07cca84f8)

</p>
</details>

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6 Pro
 - OS: GrapheneOS
 - Version: Android 15
 - NekoX v11.2.3-2

**Additional context**
Enabled Auto-Translation

**Comment by im030** [comment]
The behavior is expected and intended.
