### ISSUE TITLE
Wrong UI

### ISSUE THREAD

**Issue by 0721-Day** [im030/Momogram#30]
**Describe the bug**
Bug Description In a media-protected group chat, the forward/copy/save buttons are displayed when selecting multiple contents.

**To Reproduce**
- Open a group chat that prohibits forwarding.
- Long press the blank space on the side of the message to select messages.
- Observe that:
  - The copy/forward options are incorrectly displayed at the top.
  - The “Forward without citation” and “Save to downloads” options in the secondary menu are incorrectly displayed.

**Logcat**
This is not a serious issue, and I have not captured any logs.

**Expected behavior**
Expected Behavior In a group chat that prohibits forwarding, the forward/copy/save buttons should not be displayed.

**Screenshots**
None

**Smartphone (please complete the following information):**
 - Device: MUMUPlayer12, Honor30Pro+, Mate40Pro
 - OS: Android12（Homs4.2）

**Additional context**

I think part of this issue is related to 9805-9809 （Secondary menu）
https://raw.githubusercontent.com/dic1911/NekoX/refs/heads/lifesupport/TMessagesProj/src/main/java/org/telegram/ui/ChatActivity.java
- 9085 shuole 'currentEncryptedChat == null && !noforward'
There are still contents that need to be judged in this function

Since I am not good at Java, I can only do it here. I don't have a better way to fix it, I only know that I can add and judge one by one

**Comment by im030** [comment]
The fix will be there in the next release, join the Telegram discussion group for faster update (hotfixes are only released there).
