### ISSUE TITLE
Unable to compile ffmpeg due to missing or empty files.

### ISSUE THREAD

**Issue by dewi23** [im030/Momogram#31]
[**Describe the bug**

**To Reproduce**

**Logcat**
Settings - click version - "Enable Log", then click "Send Logs" to [@NekoXChat](https://t.me/NekoXChat) or just upload at issue.

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. MI6]
 - OS: [e.g. Android8.1]
 - Version [e.g. 5.15.0]

**Additional context**
](ninja: error: 'F:/code_demo/NekoX-lifesupport/TMessagesProj/jni/ffmpeg/build/arm64-v8a/lib/libswscale.a', needed by 'F:/code_demo/NekoX-lifesupport/TMessagesProj/build/intermediates/cxx/Debug/5rs5wq19/obj/arm64-v8a/libtmessages.49.so', missing and no known rule to make it)

**Comment by im030** [comment]
[RTFM](https://github.com/dic1911/NekoX?tab=readme-ov-file#compilation-guide)
![image](https://github.com/user-attachments/assets/8cf71386-84c9-4077-8779-d9ea405accd6)
