### ISSUE TITLE
duplicated app icon in oneui 6.1

### ISSUE THREAD

**Issue by prolletto64** [im030/Momogram#33]
**Describe the bug**
Samsung's oneui duplicates the app icon

**To Reproduce**
1. Install new momocat apk
2. You will find 2 times the app in your drawer

**Expected behavior**
Only one app

**Screenshots**
![Screenshot_20241205_081318_One UI Home.jpg](https://github.com/user-attachments/assets/6afa7ac6-10c9-4cb2-9e2a-68318e2088fe)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S24
 - OS: Android 14
 - Version: Oneui 6.1

**Additional context**
I even tried reinstalling the apk, but it still creates 2 icons.
This, however, proved me that they are the same app systemwise, just the launcher sees it twice.

**Comment by im030** [comment]
toggle use old app name in settings and the one doesn't match the option should be gone.

if the issue persists, feel free to open the issue again
